name = "fortran-s3-netcdf"
version = "0.1.0"
license = "MIT"
author = "Paul Gierz"
maintainer = "pgierz@awi.de"
copyright = "Copyright 2025, Paul Gierz"
homepage = "https://github.com/pgierz/fortran-s3-netcdf"
description = "NetCDF integration for fortran-s3-accessor - transparent S3 URIs with automatic cleanup"
categories = ["io", "cloud", "scientific-computing", "netcdf"]
keywords = ["s3", "netcdf", "climate", "earth-science", "hpc"]

[build]
auto-executables = true
auto-tests = true
auto-examples = false
module-naming = false
external-modules = ["netcdf"]
link = ["netcdff"]

[dependencies]
# Core S3 library
fortran-s3-accessor = { git = "https://github.com/pgierz/fortran-s3-accessor.git", tag = "v1.1.0" }

# Fortran stdlib for string utilities (metapackage in FPM 0.9.0+)
stdlib = "*"

# Note: NetCDF Fortran uses system-installed library (linked via [build] section above)

[dev-dependencies]
test-drive = { git = "https://github.com/fortran-lang/test-drive.git" }

[[executable]]
name = "s3_netcdf_example"
source-dir = "app"
main = "s3_netcdf_example.f90"

[install]
library = true
