name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal code or steps to reproduce the issue
      placeholder: |
        1. Call s3_nf90_open with...
        2. Then call...
        3. Observe error...
      value: |
        ```fortran
        ! Your minimal reproducible example here
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The function should return NF90_NOERR and...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: The function returned error code -51 and...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: fortran-s3-netcdf Version
      description: Which version are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: s3-accessor-version
    attributes:
      label: fortran-s3-accessor Version
      description: Which version of the parent library?
      placeholder: "1.1.0"
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other Unix
    validations:
      required: true

  - type: input
    id: compiler
    attributes:
      label: Fortran Compiler
      description: Which compiler and version?
      placeholder: "gfortran 12.2.0"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: Any error messages, stack traces, or relevant log output
      placeholder: Paste error messages here
      render: shell
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem (file sizes, network conditions, etc.)
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      description: Please verify you've completed these steps
      options:
        - label: I've searched existing issues to avoid duplicates
          required: true
        - label: I'm using the latest stable version
          required: false
        - label: I've provided a minimal reproducible example
          required: false
