name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We'd love to hear your ideas for improving fortran-s3-netcdf.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the use case?
      placeholder: I'm trying to... but currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Add a new function `s3_nf90_open_async()` that would...

        ```fortran
        ! Example API
        status = s3_nf90_open_async(uri, mode, ncid, callback)
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: I tried using... but it doesn't work because...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Performance improvement
        - New API function
        - Error handling improvement
        - Platform support
        - Documentation
        - Build system
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Needed soon
        - Medium - Would be nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who would benefit from this feature?
      placeholder: This would help users who need to...
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Suggestions
      description: Any ideas on how this could be implemented? (Optional)
      placeholder: |
        This could be implemented by:
        1. Adding a new module...
        2. Modifying the handle registry to...
    validations:
      required: false

  - type: textarea
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this require breaking API changes?
      placeholder: This would/wouldn't break existing code because...
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      options:
        - label: I've searched existing issues and PRs for similar features
          required: true
        - label: This feature aligns with the project's goals (NetCDF-S3 integration)
          required: true
        - label: I'm willing to contribute a PR for this feature
          required: false
